### PR TITLE
Tidy root dir

### LINKED ISSUE #2853: Tidy up source files
At the moment, `check_isa.cpp` and `ispc-opt.cpp` are placed in the root project directory. We may want to move it somewhere as suggested here https://github.com/ispc/ispc/pull/2851#discussion_r1598890431

There are also quite a few other source files in the root directory. We may want to organize them somehow as well.

### PR DESCRIPTION
**Pull request by nurmukhametov**
This PR fixes #2853

Scripts are moved to `scripts` folder. `check_isa` and `ispc-opt` to `tools` directory, and `test_static*` to `tests`.

### CODE REVIEW

**Comment by aneshlya** [comment]
One more idea for improving our directory structure is to move functional tests to `tests/func-tests` subfolder and move fail_db.txt to tests folder. So the `tests` directory would look like:
lit-tests/
func-tests/
CMakeLists.txt
test_static*.cpp
fail_db.txt

But it's up to you if you want to do this in this PR or not.

**Comment by nurmukhametov** [comment]
> One more idea for improving our directory structure is to move functional tests to `tests/func-tests` subfolder and move fail_db.txt to tests folder. So the `tests` directory would look like: lit-tests/ func-tests/ CMakeLists.txt test_static*.cpp fail_db.txt

It is a good idea. I have moved tests to the `func-tests` subfolder.

**Review by dbabokin — APPROVED** [review]
Looks good to me.

Cleaner folder structure is good for creating `README` files in `tests` and `scripts` with clean description of how we do testing and what scripts we have.

**Review by aneshlya — APPROVED** [review]
Looks very nice!

**Pull request merged**
