### PR TITLE
Remove non-opaque ptr mode

### LINKED ISSUE #3146: Remove non-opaque pointer mode
All supported LLVM versions [16, 19] have opaque pointer mode enabled by default. Since LLVM 17, only opaque pointers are supported. There is no need to have opaque pointer flag in cmake, CI and tests.

### PR DESCRIPTION
**Pull request by nurmukhametov**
This PR removes non-opaque pointer mode support.

This fixes #3146.

### CODE REVIEW

**Review by dbabokin — COMMENTED** [review]
Should we deprecate LLVM 16 support? I think opaque ptr mode doesn't work well for LLVM 16, so that's why we have it OFF by default.

**Comment by dbabokin** [comment]
Looking further at the logic for default setting for LLVM 16, I'm confused. Is it really on or off?

**Comment by aneshlya** [comment]
> Should we deprecate LLVM 16 support? I think opaque ptr mode doesn't work well for LLVM 16, so that's why we have it OFF by default.

We'll deprecate it when get confirmation that it's not used by UE. Opaque pointers works fine with LLVM 16. There were enabled by default in that version.

**Comment by dbabokin** [comment]
> We'll deprecate it when get confirmation that it's not used by UE. Opaque pointers works fine with LLVM 16. There were enabled by default in that version.

Ok, sounds good! I was confused by the logic and comments in `CMakeLists.txt`.

I also rely on your @aneshlya review of the implementation in this PR.

**Review by aneshlya — APPROVED** [review]
Please remove opaque pointers in one more place: https://github.com/ispc/ispc/blob/main/tests/CMakeLists.txt#L32 and it's good to go.

**Review by aneshlya — APPROVED** [review]

**Pull request merged**
