### PR TITLE
Fix for #2243. Patch for LLVM 11 & 12 and a regression test

### PR DESCRIPTION
**Pull request by dbabokin**
LLVM 12 binaries were updated, so CI is expected to pass with new regression test.

### CODE REVIEW

**Review by aneshlya — APPROVED** [review]
LGTM!

**Comment by dbabokin** [comment]
Hmmm, LLVM 11 fails with new regression test. It was passing locally for me. I will investigate.

**Comment by dbabokin** [comment]
LLVM 11 is indeed failing. The same patch needs to be applied to LLVM 11 as well. I've pushed the changes and will rebuild LLVM 11 and rerun the testing.

**Comment by dbabokin** [comment]
LLVM 11.1 binaries were updated.

**Pull request merged**
