### PR TITLE
Bandit scan + minor CI fixes

### PR DESCRIPTION
**Pull request by aneshlya**
1. Added bandit scan
2. Excluded `avx512knl-x16` from x86 testing
3. Updated result check in fmod float tests (was failing on x64 targets with -O0)
4. Added description of ispc optimization options to docs

### CODE REVIEW

**Review by dbabokin — APPROVED** [review]
Looks good, but it's surprising that library math calls with -O0 return different results, while they use exactly the same algorithms. Do you have any explanation for that?

**Comment by aneshlya** [comment]
> Looks good, but it's surprising that library math calls with -O0 return different results, while they use exactly the same algorithms. Do you have any explanation for that?

I don't have explanation for that. I was experimenting with it and I noticed that having any branch inside the `fmod` function affects the precision of the result. LLVM IR for `x - trunc(x * rcp(y)) * y` expression inside fmod function and in test looks exactly the same.

**Review by dbabokin — CHANGES_REQUESTED** [review]
Thinking about this problem, I'd like to understand the problem better before merging it. Possibly the fix should be different.

Could try running -O2 with `--opt=disable-fma`? I think this should be enough to disable all transformation that affect precision.

**Comment by aneshlya** [comment]
> Could try running -O2 with `--opt=disable-fma`? I think this should be enough to disable all transformation that affect precision.

With  `--opt=disable-fma` results are the same.

**Review by dbabokin — APPROVED** [review]
LGTM

**Pull request merged**
