### PR TITLE
LLVM patch to fix popcnt.

### PR DESCRIPTION
**Pull request by DeepakRajendrakumaran**
Checked 6.0 with/without patch and only  2 failures remain

Signed-off-by: Deepak Rajendrakumaran <deepak.rajendrakumaran@intel.com>

### CODE REVIEW

**Comment by dbabokin** [comment]
Waiting currently till the patch lands in LLVM repo - to commit the final version, but not a draft.

**Comment by DeepakRajendrakumaran** [comment]
Original llvm commit- https://github.com/llvm-mirror/llvm/commit/c4130de547959e18b1ed7026e6d21acc2f634015

**Comment by DeepakRajendrakumaran** [comment]
Messed up the merge ..will re-push with correct patch

**Comment by DeepakRajendrakumaran** [comment]
Messed up merge.

**Pull request closed without merging**
