### PR TITLE
Generate static link to the latest builds in appveyor

### PR DESCRIPTION
**Pull request by aneshlya**

### CODE REVIEW

**Comment by dbabokin** [comment]
Fix for #1515. 
Now we have static download links and can enable "trunk" in Compiler Explorer, yay!

**Comment by pbrubaker** [comment]
Really fantastic news!  Thanks for your getting this done so quickly and
thank you for your work Arina.  I will get in touch with the Compiler
Explorer team and let them know they can enable this!

**Comment by pbrubaker** [comment]
Hey guys,

I tried the links from the comments in the change and it looks like they arent working.  Am I doing something wrong?

Linux URL:
https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build/ispc-trunk-linux.tar.gz?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DUbuntu1604%2C%20LLVM_VERSION%3Dlatest

Result:
{"message":"Build job with specified name not found or access denied."}

Visual Studio URL:
https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build/ispc-trunk-windows.zip?Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202017%2C%20LLVM_VERSION%3Dlatest

Result:
{"message":"\"job\" parameter must be specified if build contains multiple jobs.\r\nParameter name: job"}

**Comment by dbabokin** [comment]
Yep, they are not working. We are trying to figure out how to make them work as expected...

**Comment by aneshlya** [comment]
Correct links are:
Linux: https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-linux.tar.gz?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DUbuntu1604%2C%20LLVM_VERSION%3Dlatest
Windows: https://ci.appveyor.com/api/projects/ispc/ispc/artifacts/build%2Fispc-trunk-windows.zip?job=Environment%3A%20APPVEYOR_BUILD_WORKER_IMAGE%3DVisual%20Studio%202017%2C%20LLVM_VERSION%3Dlatest

**Comment by pbrubaker** [comment]
Awesome, thank you @aneshlya!

**Pull request merged**
