### PR TITLE
fixes #1886 : Add warning for possible ambiguous function calls.

### LINKED ISSUE #1886: Wrong or not intuitive type cast
In the following code example I would expect that the varying function will be called. ```float``` by default is varying, so a cast to ```(float)``` should be ```(varying float)```. Instead ISPC casts it into ```(uniform float)```. The example code should print:
```
uniform func
varying func
[15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000]
```
but instead creates an infinite recursion.

Tested with ISPC 1.14.1 on Linux.

#### test.ispc
```c++
float func(float A, float B) {
        print("varying func\n");
        return A * B;
}

float func(float A, uniform float B) {
        print("uniform func\n");
        return func(A, (float)B); // adding 'varying' in the type cast fixes the problem.
}

export void test() {
        float A = 5;
        uniform float B = 3;
        print("%\n", func(A, B));
}
```

#### test.cpp
```c++
extern "C" void test(void);

int main(int argc, const char** argv) {
        test();
        return 0;
}
```

#### build steps
```bash
ispc -o test.o test.ispc
g++ test.o test.cpp
./a.out
```

### PR DESCRIPTION
**Pull request by DeepakRajendrakumaran**

### CODE REVIEW

**Comment by dbabokin** [comment]
First of all, the logic in the fix is not correct.
```c
uniform float u;
varying float v;
foo(((float)u) + u); // should trigger a warning, but will not.
```

Second, documentation should have a clear description of this problem. People will google for this warning and should get there.

Third, the warning should point out to the specific type convert.

**Comment by DeepakRajendrakumaran** [comment]
> First of all, the logic in the fix is not correct.
> 
> ```c
> uniform float u;
> foo(((float)u) + u); // should trigger a warning, but will not.
> ```
> 
> Second, documentation should have a clear description of this problem. People will google for this warning and should get there.
> 
> Third, the warning should point out to the specific type convert.

Second and third points can be addressed once we decide on exact nature of change

First point - That was by design but your point makes sense. If it's a binary operator with one ambiguous and one uniform, we still have to show warning. I'll make the change

**Comment by dbabokin** [comment]
@DeepakRajendrakumaran Please have a look at the changes that I pushed. If they look good to you, it's ready to be merged.

**Comment by DeepakRajendrakumaran** [comment]
> @DeepakRajendrakumaran Please have a look at the changes that I pushed. If they look good to you, it's ready to be merged.

LGTM

**Pull request merged**
