### PR TITLE
CMake: use explicit x86 target for dispatch

### LINKED ISSUE #2990: ISPC build on ARM targeting x86 is broken
```
[  3%] Generating share/ispc/builtins_dispatch.bc
cd /Users/dbabokin/ispc/dbabokin_ispc && /Users/dbabokin/llvm/bin-no-ncureses/bin/clang++ -x c -DREGULAR -fPIC -O2 -emit-llvm -c builtins/dispatch.c -o /Users/dbabokin/ispc/dbabokin_ispc/build/bin/../share/ispc/builtins_dispatch.bc
builtins/dispatch.c:33:36: error: invalid output constraint '=a' in asm
   33 |     __asm__ __volatile__("cpuid" : "=a"(info[0]), "=b"(info[1]), "=c"(info[2]), "=d"(info[3]) : "0"(infoType));
      |                                    ^
builtins/dispatch.c:37:36: error: invalid output constraint '=a' in asm
   37 |     __asm__ __volatile__("cpuid" : "=a"(info[0]), "=b"(info[1]), "=c"(info[2]), "=d"(info[3]) : "0"(level), "2"(count));
      |                                    ^
builtins/dispatch.c:45:53: error: invalid output constraint '=a' in asm
   45 |     __asm__ __volatile__(".byte 0x0f, 0x01, 0xd0" : "=a"(rEAX), "=d"(rEDX) : "c"(0));
      |                                                     ^
builtins/dispatch.c:57:53: error: invalid output constraint '=a' in asm
   57 |     __asm__ __volatile__(".byte 0x0f, 0x01, 0xd0" : "=a"(rEAX), "=d"(rEDX) : "c"(0));
      |                                                     ^
4 errors generated.
```

I'm macOS, but this should not be different on Linux or Windows. The problem is that `clang++` is run in "native" mode, i.e. the target is not specified. So x86 inline asm doesn't work. Any way, the dispatch is assumed to be x86 anyway.

Adding `--target=x86_64-apple-macosx` in my case fixes the problem. Though I'm not sure what generic x86 target we should use here to make it work on all platforms.

### PR DESCRIPTION
**Pull request by nurmukhametov**
This PR fixes #2990

### CODE REVIEW

**Review by dbabokin — CHANGES_REQUESTED** [review]
It doesn't work for me, as I mentioned in #2990, I'll be able to look at it a bit later.

**Comment by dbabokin** [comment]
See my comment here: https://github.com/ispc/ispc/issues/2990#issuecomment-2379825954

**Review by aneshlya — APPROVED** [review]
Looks OK to me!

**Review by dbabokin — APPROVED** [review]
This builds nicely with x86 targets enabled on my ARM MacBook.

**Pull request merged**
