### PR TITLE
Fixed Store Tests

### PR DESCRIPTION
**Pull request by e3m3**
Changes:
*   Fixed off-by-one in store-int tests.
    | `tests/store-int8-2.ispc`, `tests/store-int16-2.ispc`

Actions:
*   Commit 4bc3d5e [results](https://github.com/e3m3/ispc/actions/runs/3084396451).

### CODE REVIEW

**Comment by dbabokin** [comment]
I don't see a problem. The changes simplify the tests (in the sense that `RET[programIndex] = x[1+programIndex];` line more becomes an aligned vector copy now), but doesn't change the values, as far as I can see.

**Comment by e3m3** [comment]
> I don't see a problem. The changes simplify the tests (in the sense that `RET[programIndex] = x[1+programIndex];` line more becomes an aligned vector copy now), but doesn't change the values, as far as I can see.

Here a walkthrough of the issue:

# Before patch

## Code

```cpp
00:	#include "../test_static.isph"
01:	task void f_fu(uniform float RET[], uniform float aFOO[], uniform float b) {
02:	    uniform unsigned int8 x[2*programCount];
03:	    for (uniform int i = 0; i < 2*programCount; ++i)
04:	        x[i] = 0xff;
05:	    #pragma ignore warning(perf)
06:	    unsigned int8 val = aFOO[programIndex];
07:	    if (programIndex & 1)
08:	        x[2+programIndex] = val;
09:	    #pragma ignore warning(perf)
10:	    RET[programIndex] = x[1+programIndex];
11:	}
12:	
13:	task void result(uniform float RET[]) {
14:	    if (programIndex & 1)
15:	        RET[programIndex] = 255;
16:	    else
17:	        RET[programIndex] = programIndex;
18:	    RET[0] = 255;
19:	}
```

## State

Assume `programCount == 8`.

Line 04:

*	`programIndex		= [ 0, 		1, 		2, 		3, 		4, 		5, 		6, 		7 	]`

*	`aFOO 				= [ 1, 		2, 		3, 		4, 		5, 		6, 		7, 		8	]`

*	`x 					= [ 255,	255,	255,	255,	255,	255,	255,	255 ]`

Line 07:

*	`__mask				= [ 0,		-1,		0,		-1,		0,		-1,		0,		-1	]`

Line 08:

*	`2+programIndex 	= [ 2,		3,		4,		5,		6,		7,		8,		9	]`

*	`x 					= [ 255,	255,	1,		255,	3,		255,	5,		255 ]`

Line 10:

*	`1+programIndex 	= [ 1,		2,		3,		4,		5,		6,		7,		8	]`

*	`RET				= [ 255,	1,		255,	3,		255,	5,		255,	255	]`

Line 18:

*	`RET				= [ 255,	255,	2,		255,	4,		255,	6,		255	]`


# After patch

## Code

```cpp
00:	#include "../test_static.isph"
01:	task void f_fu(uniform float RET[], uniform float aFOO[], uniform float b) {
02:	    uniform unsigned int8 x[2*programCount];
03:	    for (uniform int i = 0; i < 2*programCount; ++i)
04:	        x[i] = 0xff;
05:	    #pragma ignore warning(perf)
06:	    unsigned int8 val = aFOO[programIndex];
07:	    if (programIndex & 1)
08:	        x[1+programIndex] = val;
09:	    #pragma ignore warning(perf)
10:	    RET[programIndex] = x[programIndex];
11:	}
12:	
13:	task void result(uniform float RET[]) {
14:	    if (programIndex & 1)
15:	        RET[programIndex] = 255;
16:	    else
17:	        RET[programIndex] = programIndex;
18:	    RET[0] = 255;
19:	}
```

## State

Assume `programCount == 8`.

Line 04:

*	`programIndex		= [ 0, 		1, 		2, 		3, 		4, 		5, 		6, 		7 	]`

*	`aFOO 				= [ 1, 		2, 		3, 		4, 		5, 		6, 		7, 		8	]`

*	`x 					= [ 255,	255,	255,	255,	255,	255,	255,	255 ]`

Line 07:

*	`__mask				= [ 0,		-1,		0,		-1,		0,		-1,		0,		-1	]`

Line 08:

*	`1+programIndex 	= [ 1,		2,		3,		4,		5,		6,		7,		8	]`

*	`x 					= [ 255,	255,	2,		255,	4,		255,	6,		255 ]`

Line 10:

*	`programIndex		= [ 0, 		1, 		2, 		3, 		4, 		5, 		6, 		7 	]`

*	`RET				= [ 255,	255,	2,		255,	4,		255,	6,		255 ]`

Line 18:

*	`RET				= [ 255,	255,	2,		255,	4,		255,	6,		255	]`

**Comment by dbabokin** [comment]
Ok, we agree that the test is correct before and after the change in term of values. I assume that the problem is in unaligned load in line 10. But this is perfectly correct ISPC code. We should generate unaligned load in this case.

**Comment by aneshlya** [comment]
I believe we agreed here that the tests are correct and the problem is with alignment. Closing this PR.

**Pull request closed without merging**
