### PR TITLE
Benchmark: Loop Unroll Fixes

### PR DESCRIPTION
**Pull request by e3m3**
Changes:
*   Reduced the run time for the loop unroll benchmark.
*   ~Formatting.~

### CODE REVIEW

**Comment by dbabokin** [comment]
I suggest doing the same as [here](https://github.com/ispc/ispc/blob/ee0bb874ccad26426765b8e1ccfbfd47a083356f/benchmarks/01_trivial/01_aossoa.cpp#L16).

And we need an explanation in the comments - so the next person changing the values understands what's going on and why these values were picked. Cache sizes are changing and ideally we should use different values based on actual cache sizes.

**Comment by dbabokin** [comment]
@Lectem looks like we found the problem with crashing benchmarks, so the problem is on our side - we use too large arrays, so it runs out of memory on your runner. Sorry for the false alarm.

**Comment by e3m3** [comment]
> I suggest doing the same as [here](https://github.com/ispc/ispc/blob/ee0bb874ccad26426765b8e1ccfbfd47a083356f/benchmarks/01_trivial/01_aossoa.cpp#L16).
> 
> And we need an explanation in the comments - so the next person changing the values understands what's going on and why these values were picked. Cache sizes are changing and ideally we should use different values based on actual cache sizes.

See commit https://github.com/ispc/ispc/pull/2396/commits/ca974615f5b281d2ce006408b0c1d6d9cec9f126.

**Review by dbabokin — APPROVED** [review]
This looks good. Note that it's not expected to pass benchmarks tests right now, because of the way these checks work - they use benchmarks from the `main` branch to validate the changes in the PR.

**Pull request merged**
