### PR TITLE
CMake: Check MSVC before adding compiler and linker options.

### PR DESCRIPTION
**Pull request by Biswa96**
This sets correct options while compiling with GCC or Clang in Win32.

### CODE REVIEW

**Comment by dbabokin** [comment]
This makes sense to me and looks like it's part of the fix for #2015.
@aneshlya could please you have a look at this?

**Review by aneshlya — APPROVED** [review]
LGTM

**Comment by Biswa96** [comment]
Speaking of cross-compilation, I compiled this in msys2/mingw-w64 environment. Though ispc is compiled it can't be used to compile other projects showing random errors with stdlib.ispc.

**Comment by dbabokin** [comment]
>Though ispc is compiled it can't be used to compile other projects showing random errors with stdlib.ispc.

This means that target files from builtins/*.ll were built incorrectly.

I'm not sure that building ispc itself in msys2/mingw-w64 environment has any practical significance. More practical goal is to build ispc using clang toolchain in MSVC. And the most useful thing is to build examples for other platforms (Linux/PS4/Android).

**Comment by dbabokin** [comment]
This PR doesn't affect the build with clang toolchain on Windows, it works both before and after the fix. I'm merging this PR.

**Pull request merged**
