### PR TITLE
alloy.py: shallow clone repo by default, add --full-checkout option

### PR DESCRIPTION
**Pull request by nurmukhametov**
Add flag `--shallow-clone` to clone `llvm` repository with `--depth=1`. It would be faster and consume less disk space.

### CODE REVIEW

**Comment by dbabokin** [comment]
Seems like useful trick. Should we use it by default? What are we missing without shallow clone? I've check standard build and it works fine.

**Comment by nurmukhametov** [comment]
We should but not all use cases are clear for me. I thought maybe CI would uncover something but it looks like that CI doesn't use `alloy.py` to build llvm, so I am not sure that it would not break something.

**Comment by dbabokin** [comment]
LLVM rebuild happens in CI, but upload of resulting binaries is a manual step.

I think we are good to use shallow copy by default. And then have full checkout as an option.

**Comment by nurmukhametov** [comment]
> LLVM rebuild happens in CI, but upload of resulting binaries is a manual step.
Can you get me a link to jobs that build LLVM?

> I think we are good to use shallow copy by default. And then have full checkout as an option.
Ok, then I will rework change to `--no-shallow-clone` option.

**Comment by nurmukhametov** [comment]
> > I think we are good to use shallow copy by default. And then have full checkout as an option.
> 
> Ok, then I will rework change to `--no-shallow-clone` option.

Made it `--full-checkout`.

**Review by dbabokin — APPROVED** [review]
LGTM.

**Pull request merged**
