### PR TITLE
Fix ispcrt tests installation

### PR DESCRIPTION
**Pull request by nurmukhametov**
Do not install ispcrt tests into build directory

Also add ispcrt-tests component target which install ispcrt_mock_tests with dependent libraries. This component install target is excluded from ALL target. It may be installed by command:

    cmake --install <dir> --component ispcrt-tests

### CODE REVIEW

**Comment by nurmukhametov** [comment]
It fixes #2482

**Comment by aneshlya** [comment]
If we enable tests as part of the build, we should install them.
The option to disable tests is `ISPCRT_BUILD_TESTS`. It can be OFF by default. But if it's ON, I prefer not to run additional commands to install tests which are already built.

**Comment by pbrubaker** [comment]
Hey all, where do we stand on this issue?

**Comment by nurmukhametov** [comment]
> Hey all, where do we stand on this issue?

My opinion is that there is no point in installing tests anywhere. Even if we do so, we need to install them at least under `CMAKE_INSTALL_PREFIX`, not inside build directory.

**Review by aneshlya — APPROVED** [review]

**Pull request merged**
