### PR TITLE
WIP : Function template

### PR DESCRIPTION
**Pull request by DeepakRajendrakumaran**

### CODE REVIEW

**Comment by stotko** [comment]
This would simplify a lot of code that currently simulates templates with some macro magic, e.g. in [Open3D](https://github.com/isl-org/Open3D/blob/8cc39dd9abc3ca95f171af4647d172052f66d862/cpp/tests/core/ParallelFor.ispc#L190). Is there a chance that we get this awesome feature in the next release, i.e. ISPC 1.17, or in the near future?

**Comment by linz2h** [comment]
Any update on this?

**Comment by dbabokin** [comment]
I'm working on the templates support right now and will create a new PR shortly. This one is abandoned, I'll close it when I create a new one.

**Comment by dbabokin** [comment]
PR https://github.com/ispc/ispc/pull/2393 supersedes this PR and is partially based on this one.
I'm closing this one.

**Pull request closed without merging**
